name: Trigger Jenkins run on merged benchmark or model PR

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://braintree.mit.edu:8080/"
        user: "kvg0"
        token: ${{ secrets.JENKINS_TOKEN }}
        job: "dev_run_benchmarks"