name: Trigger Jenkins run on merged benchmark or model PR

on:
  pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single job
      uses: GoldenspearLLC/build-jenkins-job@master
      with:
        jenkins-url: "braintree.mit.edu:8080/"
        user: "kvg0"
        jenkins-token: ${{ secrets.JENKINS_TOKEN }}
        job-path: "job/dev_run_benchmarks/"
        job-params: '{"models":"test-model", "benchmarks":"test-benchmark"}'