name: Trigger Jenkins run on merged benchmark or model PR

on:
  pull_request

jobs:
  getawscreds:
    name: Get AWS Credentials
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Read secrets from AWS Secrets Manager into environment variables
      uses: abhilash1in/aws-secrets-manager-action@v2.1.0
      with:
        secrets: brainscore-website_jenkins_access
        parse-json: false

    - name: Set secret to global env var
      run: echo "JENKINS=$"BRAINSCORE_WEBSITE_JENKINS_ACCESS" >> $GITHUB_ENV"

  parseawscreds:
    name: Parse AWS Credentials
    runs-on: ubuntu-latest
    steps:
    - name: Check if env var is set
      run: echo $JENKINS
    # - name: 


  # build:
  #   name: Build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: trigger single job
  #     uses: GoldenspearLLC/build-jenkins-job@master
  #     with:
  #       jenkins-url: "braintree.mit.edu:8080/"
  #       user: "kvg0"
  #       jenkins-token: "trigger2scoreAmodel"
  #       job-path: "dev_run_benchmarks/"
  #       job-params: '{"models":"brendel.Geirhos2021colour-top1"}'